version: '3.8'
services:
  postgres:
    image: postgres
    container_name: im-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
    ports:
      - "5431:5432"
    volumes:
      - ./repository-jdbi/src/sql:/docker-entrypoint-initdb.d
